// https://github.com/carloscuesta/gitmoji/commits/master/src/data/gitmojis.json
interface Emoji {
    readonly emoji: any;
    readonly code: any;
    readonly description: any;
    readonly description_pt_br: any;
    readonly description_pt_pt: any;
    readonly description_zh_cn: any;
}
let Gitmoji: Array<Emoji> = [
    {
        emoji: "🎨",
        code: ":art:",
        description: "Improve structure/format of the code",
        description_pt_br: "Melhorar a estrutura ou o formato do código",
        description_pt_pt: "Aprimorar a estrutura ou o formato do código",
        description_zh_cn: "改进项目结构/代码格式",
    },
    {
        emoji: "⚡️",
        code: ":zap:",
        description: "Improve performance",
        description_pt_br: "Melhorar o desempenho",
        description_pt_pt: "Aprimorar o desempenho",
        description_zh_cn: "提高性能",
    },
    {
        emoji: "🔥",
        code: ":fire:",
        description: "Remove code or files",
        description_pt_br: "Deletar o código ou os arquivos",
        description_pt_pt: "Excluir o código ou os ficheiros",
        description_zh_cn: "删除代码或文件",
    },
    {
        emoji: "🐛",
        code: ":bug:",
        description: "Fix a bug",
        description_pt_br: "Corrigir um bug",
        description_pt_pt: "Corrigir uma falha",
        description_zh_cn: "修复 BUG",
    },
    {
        emoji: "🚑",
        code: ":ambulance:",
        description: "Critical hotfix",
        description_pt_br: "Correção de bug crítico",
        description_pt_pt: "Correcção de falha crítica",
        description_zh_cn: "紧急热修复",
    },
    {
        emoji: "✨",
        code: ":sparkles:",
        description: "Introduce new features",
        description_pt_br: "Adicionar novas funções",
        description_pt_pt: "Introduzir novas funcionalidades",
        description_zh_cn: "引入新特性",
    },
    {
        emoji: "📝",
        code: ":memo:",
        description: "Add or update documentation",
        description_pt_br: "Adicionar ou atualizar a documentação",
        description_pt_pt: "Aderir ou actualizar a documentação",
        description_zh_cn: "添加或更新文件",
    },
    {
        emoji: "🚀",
        code: ":rocket:",
        description: "Deploy stuff",
        description_pt_br: "Publicar ou lançar",
        description_pt_pt: "Publicar ou lançar",
        description_zh_cn: "部署项目",
    },
    {
        emoji: "💄",
        code: ":lipstick:",
        description: "Add or update the UI and style files",
        description_pt_br: "Adicionar ou atualizar os arquivos de interface do usuário e de estilo",
        description_pt_pt: "Aderir ou actualizar os ficheiros de interface do utilizador e de estilo",
        description_zh_cn: "添加或更新 UI 样式文件",
    },
    {
        emoji: "🎉",
        code: ":tada:",
        description: "Begin a project",
        description_pt_br: "Iniciar um projeto",
        description_pt_pt: "Iniciar um projecto",
        description_zh_cn: "初次提交",
    },
    {
        emoji: "✅",
        code: ":white_check_mark:",
        description: "Add, update, or pass tests",
        description_pt_br: "Adicionar, atualizar ou passar testes",
        description_pt_pt: "Aderir, actualizar ou realizar os testes",
        description_zh_cn: "添加、更新或通过测试",
    },
    {
        emoji: "🔒️",
        code: ":lock:",
        description: "Fix security issues",
        description_pt_br: "Corrigir problemas de segurança",
        description_pt_pt: "Corrigir os problemas de segurança",
        description_zh_cn: "修复安全问题",
    },
    {
        emoji: "🔐",
        code: ":closed_lock_with_key:",
        description: "Add or update secrets",
        description_pt_br: "Adicionar ou atualizar as chaves secretas",
        description_pt_pt: "Aderir ou actualizar as chaves secretas",
        description_zh_cn: "添加或更新 secrets",
    },
    {
        emoji: "🔖",
        code: ":bookmark:",
        description: "Release/Version tags",
        description_pt_br: "Tags de lançamento ou versão",
        description_pt_pt: "Rótulos de lançamento ou versão",
        description_zh_cn: "Release / Version 标签",
    },
    {
        emoji: "🚨",
        code: ":rotating_light:",
        description: "Fix compiler/linter warnings",
        description_pt_br: "Corrigir avisos do compilador ou linter",
        description_pt_pt: "Corrigir as advertências do compilador ou linter",
        description_zh_cn: "修复编译器 / 链接器警告",
    },
    {
        emoji: "🚧",
        code: ":construction:",
        description: "Work in progress",
        description_pt_br: "Em desenvolvimento",
        description_pt_pt: "Em curso",
        description_zh_cn: "进行中的工作",
    },
    {
        emoji: "💚",
        code: ":green_heart:",
        description: "Fix CI Build",
        description_pt_br: "Corrigir a construção de CI",
        description_pt_pt: "Consertar a construção de CI",
        description_zh_cn: "修复 CI 构建",
    },
    {
        emoji: "⬇️",
        code: ":arrow_down:",
        description: "Downgrade dependencies",
        description_pt_br: "Desatualizar dependências",
        description_pt_pt: "Degradar as dependências",
        description_zh_cn: "降级依赖版本",
    },
    {
        emoji: "⬆️",
        code: ":arrow_up:",
        description: "Upgrade dependencies",
        description_pt_br: "Atualizar dependências",
        description_pt_pt: "Actualizar as dependências",
        description_zh_cn: "升级依赖版本",
    },
    {
        emoji: "📌",
        code: ":pushpin:",
        description: "Pin dependencies to specific versions",
        description_pt_br: "Fixar dependências a versões específicas",
        description_pt_pt: "Fixar as dependências a versões específicas",
        description_zh_cn: "将依赖设定为指定版本",
    },
    {
        emoji: "👷",
        code: ":construction_worker:",
        description: "Add or update CI build system",
        description_pt_br: "Adicionar ou atualizar o sistema de construção de CI",
        description_pt_pt: "Aderir ou actualizar o sistema de construção de CI",
        description_zh_cn: "添加或更新 CI 构建系统",
    },
    {
        emoji: "📈",
        code: ":chart_with_upwards_trend:",
        description: "Add or update analytics or track code",
        description_pt_br: "Adicionar ou atualizar o sistema de análise ou de rastreio de código",
        description_pt_pt: "Aderir ou actualizar análises ou código de pista",
        description_zh_cn: "添加或更新分析或跟踪代码",
    },
    {
        emoji: "♻️",
        code: ":recycle:",
        description: "Refactor code",
        description_pt_br: "Refatorar código",
        description_pt_pt: "Refactorar o código",
        description_zh_cn: "重构代码",
    },
    {
        emoji: "➕",
        code: ":heavy_plus_sign:",
        description: "Add a dependency",
        description_pt_br: "Adicionar uma dependência",
        description_pt_pt: "Aderir uma dependência",
        description_zh_cn: "添加依赖",
    },
    {
        emoji: "➖",
        code: ":heavy_minus_sign:",
        description: "Remove a dependency",
        description_pt_br: "Deletar uma dependência",
        description_pt_pt: "Excluir uma dependência",
        description_zh_cn: "移除依赖",
    },
    {
        emoji: "🔧",
        code: ":wrench:",
        description: "Add or update configuration files",
        description_pt_br: "Adicionar ou atualizar arquivos de configuração",
        description_pt_pt: "Aderir ou actualizar ficheiros de definição",
        description_zh_cn: "添加或更新配置文件",
    },
    {
        emoji: "🔨",
        code: ":hammer:",
        description: "Add or update development scripts",
        description_pt_br: "Adicionar ou atualizar scripts de desenvolvimento",
        description_pt_pt: "Aderir ou actualizar argumentos de construção",
        description_zh_cn: "添加或更新开发脚本",
    },
    {
        emoji: "🌐",
        code: ":globe_with_meridians:",
        description: "Internationalization and localization",
        description_pt_br: "Internacionalização e localização",
        description_pt_pt: "Internacionalização e localização",
        description_zh_cn: "国际化和本地化 i18n",
    },
    {
        emoji: "✏️",
        code: ":pencil2:",
        description: "Fix typos",
        description_pt_br: "Corrigir erros de digitação",
        description_pt_pt: "Corrigir os erros ortográficos",
        description_zh_cn: "修复拼写错误",
    },
    {
        emoji: "💩",
        code: ":poop:",
        description: "Write bad code that needs to be improved",
        description_pt_br: "Escrever código ruim que precisa ser melhorado",
        description_pt_pt: "Introduzir mau código que precisa ser aprimorado",
        description_zh_cn: "写不好的代码，需要改进",
    },
    {
        emoji: "⏪",
        code: ":rewind:",
        description: "Revert changes",
        description_pt_br: "Reverter alterações",
        description_pt_pt: "Reverter as mudanças",
        description_zh_cn: "还原修改",
    },
    {
        emoji: "🔀",
        code: ":twisted_rightwards_arrows:",
        description: "Merge branches",
        description_pt_br: "Mesclar as branches",
        description_pt_pt: "Fundir as ramificações",
        description_zh_cn: "合并分支",
    },
    {
        emoji: "📦",
        code: ":package:",
        description: "Add or update compiled files or packages",
        description_pt_br: "Adicionar ou atualizar arquivos compilados ou pacotes",
        description_pt_pt: "Aderir ou actualizar ficheiros compilados ou pacotes",
        description_zh_cn: "添加或更新已编译的文件或包",
    },
    {
        emoji: "👽️",
        code: ":alien:",
        description: "Update code due to external API changes",
        description_pt_br: "Atualizar código por causa das alterações externas de API",
        description_pt_pt: "Actualizar o código devido às alterações externas de API",
        description_zh_cn: "由于外部API变化而更新代码",
    },
    {
        emoji: "🚚",
        code: ":truck:",
        description: "Move or rename resources (e.g.: files, paths, routes)",
        description_pt_br: "Mover ou renomear recursos (ex.: arquivos, caminhos, rotas)",
        description_pt_pt: "Mover ou renomear recursos (ex.: ficheiros, caminhos, rotas)",
        description_zh_cn: "移动或重命名资源",
    },
    {
        emoji: "📄",
        code: ":page_facing_up:",
        description: "Add or update license",
        description_pt_br: "Adicionar ou atualizar licença",
        description_pt_pt: "Aderir ou actualizar a licença",
        description_zh_cn: "添加或更新 License",
    },
    {
        emoji: "💥",
        code: ":boom:",
        description: "Introduce breaking changes",
        description_pt_br: "Introduzir alterações que podem causar problemas",
        description_pt_pt: "Introduzir as mudanças de ruptura",
        description_zh_cn: "引入重大改变",
    },
    {
        emoji: "🍱",
        code: ":bento:",
        description: "Add or update assets",
        description_pt_br: "Adicionar ou atualizar recursos",
        description_pt_pt: "Aderir ou actualizar os recursos",
        description_zh_cn: "添加或更新资源",
    },
    {
        emoji: "♿️",
        code: ":wheelchair:",
        description: "Improve accessibility",
        description_pt_br: "Melhorar a acessibilidade",
        description_pt_pt: "Aprimorar a acessibilidade",
        description_zh_cn: "改善无障碍环境",
    },
    {
        emoji: "💡",
        code: ":bulb:",
        description: "Add or update comments in source code",
        description_pt_br: "Adicionar ou atualizar comentários no código-fonte",
        description_pt_pt: "Aderir ou actualizar os comentários no código fonte",
        description_zh_cn: "在源代码中添加或更新注释",
    },
    {
        emoji: "🍻",
        code: ":beers:",
        description: "Write code drunkenly",
        description_pt_br: "Escrever código de forma bêbada",
        description_pt_pt: "Escrever o código de forma embriagada",
        description_zh_cn: "醉醺醺的写代码",
    },
    {
        emoji: "💬",
        code: ":speech_balloon:",
        description: "Add or update text and literals",
        description_pt_br: "Adicionar ou atualizar texto e literais",
        description_pt_pt: "Aderir ou actualizar o texto e os literais",
        description_zh_cn: "添加或更新文本和文字",
    },
    {
        emoji: "🗃️",
        code: ":card_file_box:",
        description: "Perform database related changes",
        description_pt_br: "Realizar alterações relacionadas ao banco de dados",
        description_pt_pt: "Realizar as mudanças relacionadas à base de dados",
        description_zh_cn: "执行与数据库相关的更改",
    },
    {
        emoji: "🔊",
        code: ":loud_sound:",
        description: "Add or update logs",
        description_pt_br: "Adicionar ou atualizar logs",
        description_pt_pt: "Aderir ou actualizar os registos",
        description_zh_cn: "添加或更新日志",
    },
    {
        emoji: "🔇",
        code: ":mute:",
        description: "Remove logs",
        description_pt_br: "Deletar logs",
        description_pt_pt: "Excluir os registos",
        description_zh_cn: "删除日志",
    },
    {
        emoji: "👥",
        code: ":busts_in_silhouette:",
        description: "Add or update contributor(s)",
        description_pt_br: "Adicionar ou atualizar contribuidor(es)",
        description_pt_pt: "Aderir ou actualizar o(s) contribuidor(es)",
        description_zh_cn: "添加或更新贡献者",
    },
    {
        emoji: "🚸",
        code: ":children_crossing:",
        description: "Improve user experience/usability",
        description_pt_br: "Melhorar a experiência ou a usabilidade do usuário",
        description_pt_pt: "Aprimorar a experiência ou a usabilidade do utilizador",
        description_zh_cn: "提高用户体验 / 可用性",
    },
    {
        emoji: "🏗️",
        code: ":building_construction:",
        description: "Make architectural changes",
        description_pt_br: "Fazer alterações arquiteturais",
        description_pt_pt: "Realizar as alterações arquitecturais",
        description_zh_cn: "进行架构更改",
    },
    {
        emoji: "📱",
        code: ":iphone:",
        description: "Work on responsive design",
        description_pt_br: "Trabalhar no design responsivo",
        description_pt_pt: "Trabalhar na concepção reactiva",
        description_zh_cn: "响应式设计的工作",
    },
    {
        emoji: "🤡",
        code: ":clown_face:",
        description: "Mock things",
        description_pt_br: "Simular coisas",
        description_pt_pt: "Simular as coisas",
        description_zh_cn: "进行 mock 测试",
    },
    {
        emoji: "🥚",
        code: ":egg:",
        description: "Add or update an easter egg",
        description_pt_br: "Adicionar ou atualizar um easter egg",
        description_pt_pt: "Aderir ou actualizar um easter egg",
        description_zh_cn: "添加或更新一个彩蛋",
    },
    {
        emoji: "🙈",
        code: ":see_no_evil:",
        description: "Add or update a .gitignore file",
        description_pt_br: "Adicionar ou atualizar um arquivo .gitignore",
        description_pt_pt: "Aderir ou actualizar um ficheiro .gitignore",
        description_zh_cn: "添加或更新 .gitignore 文件",
    },
    {
        emoji: "📸",
        code: ":camera_flash:",
        description: "Add or update snapshots",
        description_pt_br: "Adicionar ou atualizar snapshots",
        description_pt_pt: "Aderir ou actualizar as capturas de ecrã",
        description_zh_cn: "添加或更新快照",
    },
    {
        emoji: "⚗️",
        code: ":alembic:",
        description: "Perform experiments",
        description_pt_br: "Realizar experimentos",
        description_pt_pt: "Efectuar os experimentos",
        description_zh_cn: "试验新功能",
    },
    {
        emoji: "🔍",
        code: ":mag:",
        description: "Improve SEO",
        description_pt_br: "Melhorar o SEO",
        description_pt_pt: "Aprimorar o SEO",
        description_zh_cn: "改善 SEO",
    },
    {
        emoji: "🏷️",
        code: ":label:",
        description: "Add or update types",
        description_pt_br: "Adicionar ou atualizar tipos",
        description_pt_pt: "Aderir ou actualizar as etiquetas",
        description_zh_cn: "添加或更新类型",
    },
    {
        emoji: "🌱",
        code: ":seedling:",
        description: "Add or update seed files",
        description_pt_br: "Adicionar ou atualizar arquivos de seed",
        description_pt_pt: "Aderir ou actualizar os ficheiros de seed",
        description_zh_cn: "添加或更新 SEED 文件",
    },
    {
        emoji: "🚩",
        code: ":triangular_flag_on_post:",
        description: "Add, update, or remove feature flags",
        description_pt_br: "Adicionar, atualizar ou remover as bandeiras de funcionalidades",
        description_pt_pt: "Aderir, actualizar ou excluir as bandeiras de funcionalidades",
        description_zh_cn: "添加、更新或删除特性标志",
    },
    {
        emoji: "🥅",
        code: ":goal_net:",
        description: "Catch errors",
        description_pt_br: "Pegar erros",
        description_pt_pt: "Capturar os erros",
        description_zh_cn: "捕获异常",
    },
    {
        emoji: "💫",
        code: ":dizzy:",
        description: "Add or update animations and transitions",
        description_pt_br: "Adicionar ou atualizar animações e transições",
        description_pt_pt: "Aderir ou actualizar as animações e as transições",
        description_zh_cn: "添加或更新动画和过场",
    },
    {
        emoji: "🗑️",
        code: ":wastebasket:",
        description: "Deprecate code that needs to be cleaned up",
        description_pt_br: "Deprecar código que precisa de limpeza",
        description_pt_pt: "Depreciar o código que precisa de ser limpo",
        description_zh_cn: "需要清理的废弃代码",
    },
    {
        emoji: "🛂",
        code: ":passport_control:",
        description: "Work on code related to authorization, roles and permissions",
        description_pt_br: "Trabalhar no código relacionado à autorização, funções e permissões",
        description_pt_pt: "Trabalho em código relacionado com autorização, papéis e permissões",
        description_zh_cn: "编写与授权、角色和权限有关的代码",
    },
    {
        emoji: "🩹",
        code: ":adhesive_bandage:",
        description: "Simple fix for a non-critical issue",
        description_pt_br: "Solução simples para um problema não crítico",
        description_pt_pt: "Solução simples para um problema não crítico",
        description_zh_cn: "简单修复非关键性问题",
    },
    {
        emoji: "🧐",
        code: ":monocle_face:",
        description: "Data exploration/inspection",
        description_pt_br: "Exploração ou inspeção de dados",
        description_pt_pt: "Exploração ou inspecção de dados",
        description_zh_cn: "数据探索 / 数据巡检",
    },
    {
        emoji: "⚰️",
        code: ":coffin:",
        description: "Remove dead code",
        description_pt_br: "Remover código morto",
        description_pt_pt: "Excluir o código morto",
        description_zh_cn: "删除无效代码",
    },
    {
        emoji: "🧪",
        code: ":test_tube:",
        description: "Add a failing test",
        description_pt_br: "Adicionar um teste de falha",
        description_pt_pt: "Aderir um teste de falha",
        description_zh_cn: "添加一个失败的测试",
    },
    {
        emoji: "👔",
        code: ":necktie:",
        description: "Add or update business logic",
        description_pt_br: "Adicionar ou atualizar lógica de negócios",
        description_pt_pt: "Aderir ou actualizar a lógica empresarial",
        description_zh_cn: "添加或更新业务逻辑",
    },
    {
        emoji: "🩺",
        code: ":stethoscope:",
        description: "Add or update healthcheck",
        description_pt_br: "Adicionar ou atualizar checagem de saúde",
        description_pt_pt: "Aderir ou actualizar a verificação de saúde",
        description_zh_cn: "添加或更新健康检查",
    },
    {
        emoji: "🧱",
        code: ":bricks:",
        description: "Infrastructure related changes",
        description_pt_br: "Alterações relacionadas à infraestrutura",
        description_pt_pt: "Mudanças relacionadas com infraestrutura",
        description_zh_cn: "与基础设施有关的变化",
    },
    {
        emoji: "🧑‍💻",
        code: ":technologist:",
        description: "Improve developer experience",
        description_pt_br: "Melhorar a experiência do desenvolvedor",
        description_pt_pt: "Aprimorar a experiência do programador",
        description_zh_cn: "改善开发者体验",
    },
    {
        emoji: "💸",
        code: ":money_with_wings:",
        description: "Add sponsorships or money related infrastructure",
        description_pt_br: "Adicionar patrocínios ou infraestrutura relacionada a dinheiro",
        description_pt_pt: "Acrescentar patrocínios ou infra-estruturas relacionadas com dinheiro",
        description_zh_cn: "添加赞助或与金钱相关的基础设施",
    },
];
export default Gitmoji;
